name: LibraryBuild
on: [push, pull_request]
jobs:
  build:
    name: Test compiling examples for ESP8266
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v3
      with:
        arduino-board-fqbn: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
        platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
        required-libraries: ESP8266WiFi, ArduinoJson, WiFiClient, ESP8266WebServer, ESP8266HTTPClient
        sketches-exclude: WhistleSwitch 50Hz
        build-properties: '{"WhistleSwitch": "-DDEBUG -DFREQUENCY_RANGE_LOW", "SimpleFrequencyDetector": "-DINFO"}'
        sketch-names:
          ArduinoDHT.ino
