name: Build NodeMCU 1.0 (ESP8266)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      with:
        arduino-cli-version: 0.18.3
    - name: Install ESP8266 core
      run: arduino-cli core install esp8266:esp8266
    - name: Build sketch
      run: arduino-cli compile --fqbn esp8266:esp8266:nodemcuv2:xtal=80,vt=flash,exception=disabled,ssl=all,eesz=4M1M,led=2,ip=lm2f,dbg=Disabled,lvl=None____,wipe=none,baud=921600 .\Arduino\ArduinoDHT\ArduinoDHT.ino
