name: Build NodeMCU 1.0 (ESP8266)

on: [push]

env:
  ARDUINO_IDE_VERSION: 1.8.13
  ARDUINO_BOARD_MANAGER_URL: https://arduino.esp8266.com/stable/package_esp8266com_index.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Arduino CLI
      uses: actions/setup-arduino-cli@v1
      with:
        arduino-cli-version: 0.10.0

    - name: Install ESP8266 Board
      run: |
        arduino-cli core update-index
        arduino-cli core install esp8266:esp8266
        arduino-cli config init
        arduino-cli config set board_manager.additional_urls ${ARDUINO_BOARD_MANAGER_URL}
        arduino-cli core update-index
        arduino-cli core install esp8266:esp8266

    - name: Build Sketch
      run: |
        arduino-cli compile --fqbn esp8266:esp8266:nodemcu Arduino/ArduinoDHT/ArduinoDHT.ino

    - name: Upload Sketch
      if: always()
      run: |
        arduino-cli upload -p /dev/ttyUSB0 --fqbn esp8266:esp8266:nodemcu Arduino/ArduinoDHT/ArduinoDHT.ino

    - name: Display log output
      run: |
        echo "Build completed!"
