name: Build NodeMCU 1.0 (ESP8266)

on: [push]

env:
  ARDUINO_IDE_VERSION: 1.8.13
  ARDUINO_BOARD_MANAGER_URL: https://arduino.esp8266.com/stable/package_esp8266com_index.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Arduino IDE
      uses: actions/setup-arduino@v1
      with:
        arduino-version: ${{ env.ARDUINO_IDE_VERSION }}

    - name: Install ESP8266 Board
      run: |
        arduino --install-boards "esp8266:esp8266"
        arduino --board-manager-pref "boardsmanager.additional.urls=${ARDUINO_BOARD_MANAGER_URL}"
        arduino --install-boards "esp8266:esp8266"

    - name: Build Sketch
      run: |
        arduino --verify --board esp8266:esp8266:nodemcu Arduino/ArduinoDHT/ArduinoDHT.ino

    - name: Upload Sketch
      if: always()
      run: |
        arduino --upload --board esp8266:esp8266:nodemcu --port /dev/ttyUSB0 Arduino/ArduinoDHT/ArduinoDHT.ino

    - name: Display log output
      run: |
        echo "Build completed!"
